name: CI
on: [push, pull_request]
jobs:
  build_project:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

  build_examples:
    name: Build project examples

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest]
        example:
          [
            'react-craco',
            'react-webpack-5-experiments',
            'webpack-5-experiments',
            'webpack-bundler',
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples/${{ matrix.example }}

      - name: Build
        run: CI=false yarn build
        working-directory: examples/${{ matrix.example }}
